SELECT TITLE, 
BOARD.BOARD_ID, 
REPLY_ID, 
REPLY.WRITER_ID, 
REPLY.CONTENTS, 
DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
from USED_GOODS_REPLY as REPLY
left join USED_GOODS_BOARD as BOARD 
on REPLY.BOARD_ID = BOARD.BOARD_ID
where DATE_FORMAT(BOARD.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY REPLY.CREATED_DATE, TITLE