SELECT USER_ID, NICKNAME, sum(PRICE) as TOTAL_SALES
FROM USED_GOODS_USER as USER
join USED_GOODS_BOARD as BOARD
ON USER.USER_ID = BOARD.WRITER_ID
where STATUS = 'DONE' 
GROUP BY USER_ID
having TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES