SELECT REVIEW.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW.REVIEW_SCORE),2) AS SCORE
from REST_REVIEW as REVIEW
left join REST_INFO as INFO
on REVIEW.REST_ID = INFO.REST_ID
GROUP BY REVIEW.REST_ID
HAVING ADDRESS like '서울%'
order by SCORE desc, FAVORITES desc